### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [2]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [109]:
#There are several ways to get help on a numpy array.
#You can use the lookfor feature to search for specific keywords.
#You can also use info or source to get more specific information (for example for a function, class or module)
#As instructed to do here-you could also call dir on the array to obtain specific methods and attributes available for use.
dir(np.array)
dir(car)
#To be honest, I was not 100% sure what this question was asking or how to provide the best answer. 
#If you wanted to use a method or attribute, you could use the help function to better understand those options.
#car appears to have more items in its directory so presumably would have more methods and attributes available to us to use.



['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [11]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

object
float64
float64
object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#It is called an alias. An alias is used when data is given more than one name

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [15]:
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)
print(displacement.ndim)
print(horsepower.ndim)
print(weight.ndim)
print(acceleration.ndim)
print(model.ndim)
print(origin.ndim)


1
1
1
1
1
1
1
1
1


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [19]:
mpg12=mpg*12
mpg_div_3=mpg/3
mpg_power4=mpg**4
mpg_sqrt=np.sqrt(mpg)

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [29]:
sum_horsepower=np.sum([horsepower])
print("sum of horsepower =",sum_horsepower)

min_horsepower=np.amin(horsepower, axis=0)
print("min of horsepower =",min_horsepower)
#This one is clearly incorrect as 0 horsepower doesn't make any sense in this context (car)

max_horsepower=np.amax(horsepower)
print("max of horsewpower =",max_horsepower)

median_horsepower=np.median(horsepower)
print("median of horsepower =",median_horsepower)

from scipy import stats
mode_horsepower=stats.mode(horsepower)
print("mode of horsepower =",mode_horsepower)



sum of horsepower = 42033.0
min of horsepower = 0.0
max of horsewpower = 230.0
median of horsepower = 93.5
mode of horsepower = ModeResult(mode=array([150.]), count=array([22]))


7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [38]:
#first_five=np.acceleration([0:4])
#print(first_five)
first_five=acceleration[0:5]
print(first_five)

size_acceleration=acceleration.size
print(size_acceleration)
rest_acceleration=acceleration[5:407]


[12.  11.5 11.  12.  10.5]
406


8. Show how to select the number `99` in the array below. 

In [40]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [41]:
#This will select the value of 99 in the numpy array. 
#References for index is [1,2]because indexing starts at 0 in python
select_99[1,2]

#I wanted to double check that this worked so I printed the value indexed.
print(select_99[1,2])

99


9. Select the last element in each subarray (do this with one operation.)

In [43]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [84]:
print(select_more[0,2], select_more[1,2], select_more[2,2])

#Another way to do this that is more general/simple
print(select_more[:,-1])


3 6 9
[3 6 9]


10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [53]:
#np.lookfor('log')
#print(np.lookfor('log'))

natural_log_of_mpg=np.log(mpg)
#print(natural_log_of_mpg)

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [56]:
print(np.unique(origin))

['Europe' 'Japan' 'US']


12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [74]:

two_D_array = np.array ([[1, 2, 3],[4, 5, 6]])
print("2D array dimensions =", two_D_array.ndim)
print("2D array shape =", two_D_array.shape)

three_D_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D array dimensions =", three_D_array.ndim)
print("3D array shape =", three_D_array.shape)

four_D_array=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]])
print("4D array dimensions =", four_D_array.ndim)
print("4D array shape =", four_D_array.shape)


2D array dimensions = 2
2D array shape = (2, 3)
3D array dimensions = 3
3D array shape = (2, 2, 3)
4D array dimensions = 4
4D array shape = (1, 4, 2, 3)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [87]:
US_only_bool=origin=='US'
print(US_only_bool)

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [93]:
US_only_array=car[origin=='US']
print(US_only_array)
print(len(US_only_array))
print(len(car))

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Chevrolet Chevelle Concours (sw)' 'Ford Torino (sw)'
 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)' 'Dodge Challenger SE'
 "Plymouth 'Cuda 340" 'Ford Mustang Boss 302' 'Chevrolet Monte Carlo'
 'Buick Estate Wagon (sw)' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200' 'Hi 1200D'
 'Chevrolet Vega 2300' 'Ford Pinto' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Country Squire (sw)' 'Pontiac Safari (sw)'
 'AMC Hornet Sportabout (sw)' 'Chevrolet Vega (sw)' 'Pontiac Firebird'
 'Ford Mustang' 'Mercury Capri 2000' 'Plymouth Cricket'
 'Dodge Colt Hardtop' 'Chevrolet Vega' 'Ford

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [108]:
#An identity matrix multiplied by a matrix of the same size returns the original matrix.
identity=np.identity(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


2. Transpose the following array. 

In [111]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [112]:
np.transpose(transpose_me)
print(np.transpose(transpose_me))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

In [ ]:
#arr1 and arr2 are of different sizes (3x3 vs 3x2). You cannot multiple arrays of different sizes as you multiply .

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [99]:

Europe_hp=horsepower[origin=='Europe']
#print(Europe_hp)

avg_Europe_hp=np.average(horsepower[origin=='Europe'])
print('average horsepower of Europe cars =',avg_Europe_hp)

average horsepower of Europe cars = 78.78082191780823


5. On average are Japanse cars more fuel efficient than US cars? 

In [104]:
Japan_mpg=mpg[origin=='Japan']
#print(Japan_mpg)

avg_Japan_mpg=np.average(mpg[origin=='Japan'])
print('average mpg of Japanese cars =',avg_Japan_mpg)

US_mpg=mpg[origin=='US']
#print(US_mpg)

avg_US_mpg=np.average(mpg[origin=='US'])
print('average mpg of US cars =',avg_US_mpg)

if avg_Japan_mpg > avg_US_mpg:
    print('Japanese cars are more fuel efficient than US cars')
else:
    print('US cars are more fuel efficient than Japanese cars')

average mpg of Japanese cars = 30.450632911392404
average mpg of US cars = 19.688188976377955
Japanese cars are more fuel efficient than US cars


6. What is the correlation coefficient of `mpg` and `weight`?

In [107]:
corr_coef_mpg_weight=np.corrcoef(mpg,weight)
print(corr_coef_mpg_weight)

#The negative correlation coefficient is implying that as weight increases, the mpg (fuel efficiency)decreases

[[ 1.         -0.78750994]
 [-0.78750994  1.        ]]


7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
#Python lists can contain heterogeneous data types (for example, strings and floats could be contained in the same list)
#On the other hand, arrays must contain homogeneous data.
#An array would be preferred when you want to perform operations on the data (you cannot do that on a list)
#However, if you wanted to store multiple types of data in a single structure, the list would be preferred.